/** Common course languages, by English display name. Static list — no runtime i18n needed here. */
export const LANGUAGES: string[] = [
  "English",
  "Mandarin Chinese",
  "Hindi",
  "Spanish",
  "French",
  "Standard Arabic",
  "Bengali",
  "Portuguese",
  "Russian",
  "Urdu",
  "Indonesian",
  "German",
  "Japanese",
  "Swahili",
  "Marathi",
  "Telugu",
  "Turkish",
  "Tamil",
  "Yue Chinese (Cantonese)",
  "Vietnamese",
  "Korean",
  "Wu Chinese",
  "Italian",
  "Punjabi",
  "Gujarati",
  "Persian (Farsi)",
  "Malayalam",
  "Hausa",
  "Odia",
  "Burmese",
  "Thai",
  "Amharic",
  "Ukrainian",
  "Polish",
  "Kannada",
  "Yoruba",
  "Sindhi",
  "Uzbek",
  "Malay",
  "Igbo",
  "Nepali",
  "Romanian",
  "Dutch",
  "Sinhala",
  "Zulu",
  "Khmer",
  "Chichewa",
  "Somali",
  "Kazakh",
  "Hungarian",
  "Greek",
  "Czech",
  "Swedish",
  "Belarusian",
  "Azerbaijani",
  "Serbian",
  "Bulgarian",
  "Danish",
  "Finnish",
  "Slovak",
  "Norwegian",
  "Hebrew",
  "Croatian",
  "Lithuanian",
  "Latvian",
  "Estonian",
  "Slovenian",
  "Georgian",
  "Armenian",
  "Mongolian",
  "Tagalog (Filipino)",
  "Pashto",
  "Kurdish",
  "Xhosa",
  "Afrikaans",
  "Albanian",
  "Icelandic",
  "Irish",
  "Welsh",
  "Maltese",
  "Luxembourgish",
  "Basque",
  "Catalan",
  "Galician",
];
